services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    profiles: ["infra"]
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
    shm_size: 128mb
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Run 'dotnet migrations' to update 'postgres'
  run_migrations:
    container_name: run_migrations
    image: mcr.microsoft.com/dotnet/sdk:10.0
    profiles: ["infra"]
    working_dir: /src
    volumes:
      - ./:/src
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASS}"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
        dotnet tool install --global dotnet-ef && 
        dotnet tool restore && 
        dotnet build --configuration Release &&
        /root/.dotnet/tools/dotnet-ef database update --project /src/src/Infrastructure/Zeiss.Products.Infrastructure --startup-project /src/src/Presentation/Zeiss.Products.WebApi
      "

  # Seeds the database (postgres) if 'run_migrations' completes with success
  seed_postgress:
    container_name: seed_postgress
    image: postgres:15-alpine
    profiles: ["infra"]
    depends_on:
      run_migrations:
        condition: service_completed_successfully
    environment:
      PGPASSWORD: "${POSTGRES_PASS}"
    volumes:
      - ./dev-data/sql:/data
    entrypoint: >
      bash -c "for f in /data/*.sql; do
                  echo Running $$f;
                  psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f \"$$f\";
               done"
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-alpine
    profiles: ["infra"]
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq
    restart: always
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    profiles: ["infra"]
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    environment:
        - node.name=es01
        - discovery.type=single-node
        - xpack.security.enabled=false
        - ingest.geoip.downloader.enabled=false
        - ELASTIC_USERNAME=${ELASTIC_USER}
        - ELASTIC_PASSWORD=${ELASTIC_PASS}
        - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    volumes:
      - elastic:/usr/share/elasticsearch/data
    restart: always

  redis:
    container_name: redis
    image: redis:6-alpine
    profiles: ["infra"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data
    command: >
      redis-server --requirepass ${REDIS_PASS} --appendonly yes
    restart: always
    
  webapi:
    container_name: webapi
    profiles: ["api"]
    build:
      context: .
      dockerfile: src/Presentation/Zeiss.Products.WebApi/Dockerfile
    ports:
      - "${WEBAPI_HTTP_PORT}:${WEBAPI_HTTP_PORT}"
      - "${WEBAPI_HTTPS_PORT}:${WEBAPI_HTTPS_PORT}"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:${WEBAPI_HTTP_PORT};https://0.0.0.0:${WEBAPI_HTTPS_PORT}"
      ASPNETCORE_HTTP_PORTS: ${WEBAPI_HTTP_PORT},${WEBAPI_HTTPS_PORT}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${WEBAPI_HTTPS_CERT_PATH}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${WEBAPI_HTTPS_CERT_PASS}
      ConnectionStrings__Postgres: "Host=postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASS}"
      Jwt__SecretKey: ${WEBAPI_JWT_SECRETKEY}
      Jwt__Issuer: ${WEBAPI_JWT_ISSUER}
      Jwt__Audience: ${WEBAPI_JWT_AUDIENCE}
      Jwt__TokenExpirationMinutes: ${WEBAPI_JWT_EXP_MIN}
      RabbitMq__Host: rabbitmq
      RabbitMq__Port: ${RABBITMQ_PORT}
      RabbitMq__VirtualHost: ${RABBITMQ_VHOST}
      RabbitMq__Username: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASS}
      Redis__ConnectionString: "redis:${REDIS_PORT},password=${REDIS_PASS},Ssl=False,abortConnect=False"
      Redis__RecordRetentionInSeconds: 30
      Elasticsearch__Uri: http://localhost:${ELASTIC_PORT}
      Elasticsearch__IndexFormat: ${ELASTIC_INDEX_FORMAT}
    
volumes:
  postgres:
    driver: local
  rabbitmq:
    driver: local
  elastic:
    driver: local
  redis:
    driver: local