services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "zeiss-products"
      POSTGRES_USER: "ze1ss"
      POSTGRES_PASSWORD: "ze1s<s>-pr0ds"
    shm_size: 128mb
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ze1ss -d zeiss-products"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Run 'dotnet migrations' to update 'postgres'
  run_migrations:
    container_name: run_migrations
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /src
    volumes:
      - ./:/src
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=zeiss-products;Username=ze1ss;Password=ze1s<s>-pr0ds"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
        dotnet tool install --global dotnet-ef && 
        dotnet tool restore && 
        dotnet build --configuration Release &&
        /root/.dotnet/tools/dotnet-ef database update --project /src/src/Infrastructure/Zeiss.Products.Infrastructure --startup-project /src/src/Presentation/Zeiss.Products.WebApi
      "

  # Seeds the database (postgres) if 'run_migrations' completes with success
  seed_postgress:
    container_name: seed_postgress
    image: postgres:15-alpine
    depends_on:
      run_migrations:
        condition: service_completed_successfully
    environment:
      PGPASSWORD: "ze1s<s>-pr0ds"
    volumes:
      - ./data:/data
    entrypoint: >
      bash -c "for f in /data/*.sql; do
                  echo Running $$f;
                  psql -h postgres -U ze1ss -d zeiss-products -f \"$$f\";
               done"
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "ze1s"
      RABBITMQ_DEFAULT_PASS: "ze-rabbit"
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq
    restart: always
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    ports:
      - "9200:9200"
    environment:
        - node.name=es01
        - discovery.type=single-node
        - xpack.security.enabled=false
        - ingest.geoip.downloader.enabled=false
        - ELASTIC_USERNAME=ze1ss
        - ELASTIC_PASSWORD=ze-l4ast1c
        - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    volumes:
      - elastic:/usr/share/elasticsearch/data
    restart: always

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:ro
      - redis:/data
    command: >
      redis-server
      --aclfile /usr/local/etc/redis/users.acl
      --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "--user", "appuser", "--pass", "ze1ss<caching>-sync", "--no-auth-warning", "ping"]
    restart: always
    
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: src/Presentation/Zeiss.Products.WebApi/Dockerfile
    ports:
      - "5056:5056"
      - "7192:7192"
    environment:
      #ASPNETCORE_URLS: "http://0.0.0.0:5056;https://0.0.0.0:7192"
      ASPNETCORE_URLS: "http://0.0.0.0:5056"
      ASPNETCORE_HTTP_PORTS: 5056
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=zeiss-products;Username=ze1ss;Password=ze1s<s>-pr0ds"
      Jwt__SecretKey: "emdlLzUtUxchhbGxlbmdlLzUtY2WNvZGUUxchhbGx"
      Jwt__Issuer: "Docker - Zeiss Products"
      Jwt__Audience: "zeiss-clients"
      Jwt__TokenExpirationMinutes: 15
      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__VirtualHost: "/"
      RabbitMq__Username: "ze1s"
      RabbitMq__Password: "ze-rabbit"
      Redis__ConnectionString: "redis:6379,user=appuser,password=ze1ss<caching>-sync,Ssl=False,abortConnect=False"
      Redis__RecordRetentionInSeconds: 30
      Elasticsearch__Uri: 
      Elasticsearch__IndexFormat: "ze-docker-product-logs-{0:yyyy.MM.dd}"
    
volumes:
  postgres:
    driver: local
  rabbitmq:
    driver: local
  elastic:
    driver: local
  redis:
    driver: local